# This workflow gives a friendly nudge to issues and PRs that have been taking a nap for a while.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Keep Issues and PRs Fresh

on:
  schedule:
  - cron: '33 12 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: |
          ğŸŒŸ **Hey there!** ğŸŒŸ
          It looks like this issue has been snoozing for a bit. If youâ€™re still working on it, weâ€™d love to hear from you! ğŸš€
          If itâ€™s no longer relevant, no worriesâ€”just give us a shout, and weâ€™ll tidy things up. Thanks for helping us keep the repo fresh! ğŸŒ±
          
        stale-pr-message: |
          ğŸ‘‹ **Hello there!** ğŸ‘‹
          Your pull request seems to be enjoying a long vacation. ğŸ–ï¸ If youâ€™re still polishing it, weâ€™d love to see the updates! ğŸ”„
          If itâ€™s not on your to-do list anymore, no problemâ€”just let us know, and weâ€™ll help get things back on track. Thanks for keeping things moving! ğŸš€
          
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
